[2024-06-19T03:51:04.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T03:51:04.548+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-19T03:51:04.559+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-19T03:51:04.559+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-06-19T03:51:04.597+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-06-18 00:00:00+00:00
[2024-06-19T03:51:04.610+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8309) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T03:51:04.613+0000] {standard_task_runner.py:63} INFO - Started process 8318 to run task
[2024-06-19T03:51:04.613+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_postgres', 'extract_data', 'scheduled__2024-06-18T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_postgres.py', '--cfg-path', '/tmp/tmpl70c1jcd']
[2024-06-19T03:51:04.617+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask extract_data
[2024-06-19T03:51:04.699+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [running]> on host 7709186783c9
[2024-06-19T03:51:04.854+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='candratama' AIRFLOW_CTX_DAG_ID='extract_data_from_postgres' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T00:00:00+00:00'
[2024-06-19T03:51:04.855+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T03:51:04.891+0000] {base.py:84} INFO - Using connection ID '***_db_conn' for task execution.
[2024-06-19T03:51:04.919+0000] {logging_mixin.py:188} INFO -    id         name
0   1     can_edit
1   2     can_read
2   3   can_create
3   4   can_delete
4   5  menu_access
[2024-06-19T03:51:04.919+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-19T03:51:04.920+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T03:51:04.936+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=extract_data_from_postgres, task_id=extract_data, run_id=scheduled__2024-06-18T00:00:00+00:00, execution_date=20240618T000000, start_date=20240619T035104, end_date=20240619T035104
[2024-06-19T03:51:04.991+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T03:51:05.022+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T03:51:05.032+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
